services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: pruebapractica
          property: connectionString

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run src/front/app.py --server.port 10001 --server.headless true"
    envVars:
      - key: PORT
        value: 10001
      - key: DATABASE_URL
        fromDatabase:
          name: pruebapractica
          property: connectionString
